Using the services methods from fip-commons
sighupio/service-endpoints-check pull request #16
Opened 2021-07-08 06:13 UTC by nandajavarma

2021-07-09 14:13 UTC, angelbarrera92 commented on examples/redis-deployment/namespace.yaml
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
Is this intended?

2021-07-09 14:15 UTC, angelbarrera92 commented on internal/config/config.go
> +func NewSecConfig() *SecConfig {
If you are exposing a constructor... Is it required to expose the `SecConfig` type?
In other words...
what happens if you rename the `SecConfig` type to `secConfig`?

2021-07-09 14:15 UTC, angelbarrera92 commented on internal/services/main_test.go
> +package services
If the file has no content, feel free to remove it

2021-07-09 14:16 UTC, angelbarrera92 commented on cmd/service-endpoints-check/main.go
> +		ctx := context.Background()
Instead of using a new context (background), try to use the cobra context. Something like `cmd.Context()`

2021-07-09 14:18 UTC, angelbarrera92 requested changes
Overall looks good, just take a look to the comments i left in the PR

2021-07-09 14:19 UTC, nandajavarma commented on examples/redis-deployment/namespace.yaml
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
nope. fixed. 🤦

2021-07-09 14:21 UTC, nandajavarma commented on internal/config/config.go
> +func NewSecConfig() *SecConfig {
SecConfig is imported in other files. To define type. like `var cfg *config.SecConfig`

2021-07-09 14:22 UTC, nandajavarma commented on cmd/service-endpoints-check/main.go
> +		ctx := context.Background()
oooh great point! still getting my head around contexts! will do

2021-07-09 14:23 UTC, nandajavarma commented on internal/services/main_test.go
> +package services
done!

2021-07-12 09:26 UTC, angelbarrera92 commented on internal/config/config.go
> +func NewSecConfig() *SecConfig {
What about:

`cfg := NewSecConfig()`

2021-07-12 09:38 UTC, nandajavarma commented on internal/config/config.go
> +func NewSecConfig() *SecConfig {
we have to still use SecConfig  outside as a type. Marking it as resolved.

2021-07-12 09:39 UTC, merged