WIP: Adding the endpoints check for services
sighupio/service-endpoints-check pull request #2
Opened 2021-06-18 10:53 UTC by nandajavarma

2021-06-22 07:30 UTC, angelbarrera92 commented on cmd/root.go
> +func initConfig() {
I like this method :)

2021-06-22 07:31 UTC, angelbarrera92 commented on main.go
> +}
Do we need this file?

2021-06-22 07:32 UTC, angelbarrera92 commented on pkg/client/client.go
> +			kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
Why we are using here `flag` instead of passing the argument from `cobra`? Am I missing something?

2021-06-22 07:33 UTC, angelbarrera92 commented on pkg/services/main.go
> +	fmt.Println(endpointLists)
We have to consider using a proper logging utility (same or similar to the one used in `furyctl`

2021-06-22 07:38 UTC, angelbarrera92 requested changes
Overall, looks good.

Maybe in the future, we can consider using the "main" (cobra one¿?¿?)context in `kube` client. What do you think?

2021-06-22 09:33 UTC, nandajavarma commented on pkg/services/main.go
> +	fmt.Println(endpointLists)
It was a stupid debug  printing. I have removed it. Generally everywhere I have used logrus instead.

2021-06-24 10:36 UTC, angelbarrera92 commented on Makefile
> +e2e-test: check-docker check-kind check-kubectl check-bats check-envsubst build-release
❤️

2021-06-24 10:36 UTC, angelbarrera92 commented on build/builder/Dockerfile
> +ENTRYPOINT ["/service-endpoints-check"]
Sounds legiti!

2021-06-24 10:37 UTC, angelbarrera92 commented on cmd/service-endpoints-check/main.go
> +	rootCmd.PersistentFlags().StringVar(&kubeCfgFile, "kubeconfig", "",
Did you think about using the same env variable `kubectl` uses to use it in this CLI? `KUBECONFIG`¿?

2021-06-24 10:41 UTC, angelbarrera92 commented on deployments/cluster-role-binding.yaml
> +kind: ClusterRoleBinding
I think we have to consider creating a `RoleBinding` instead of a `ClusterRoleBinding`.

- If this check is used only to monitor the application (in a namespace), we can consider moving to `RoleBinding`. 
- If the Application concepts spread more than one namespace, is fine using `ClusterRoleBinding`

What do you think?

2021-06-24 10:41 UTC, angelbarrera92 commented on deployments/cluster-role-binding.yaml
> +    namespace: default
Ensure in the docs the deployment will happen in the `default` namespace (by default).

2021-06-24 10:41 UTC, angelbarrera92 commented on deployments/cluster-role-binding.yaml
> +    namespace: default
writing it down

2021-06-24 10:45 UTC, angelbarrera92 commented on deployments/kustomization.yaml
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
What about creating a new subdir to host the `kustomize` project?
I mean... what if we want to provide both? `kustomize` and `helm` charts?

Something like:

- `deployments/kustomize/kustomization.yaml`
- `deployments/helm/chart.yaml`

What do you think?

2021-06-24 10:45 UTC, angelbarrera92 commented on deployments/role-binding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Don't get why we need both, `RoleBinding` and `ClusterRoleBinding`. I think worth speaking about it as mentioned above :)

2021-06-24 10:46 UTC, angelbarrera92 commented on deployments/cluster-role-binding.yaml
> +  namespace: default
Avoid setting the namespace in the `deployments` dir

2021-06-24 10:47 UTC, angelbarrera92 commented on examples/cluster-role-binding.yaml
> +    namespace: default
Ensure in the docs the deployment will happen in the default namespace (by default) by writing it down :)

2021-06-24 10:51 UTC, angelbarrera92 commented on scripts/e2e/run.sh
> +KUBECONFIG=$(pwd)/kubeconfig TEST_PATH=$(pwd)/scripts/e2e/ CONTAINER_IMAGE=${1} bats -t ./scripts/e2e/tests.sh
What is `TEST_PATH`? Do you need a temp dir?
Bats provides you an env variable containing a temp directory path: `BATS_RUN_TMPDIR`

*source: [https://github.com/bats-core/bats-core/blob/master/docs/source/writing-tests.md#special-variables](https://github.com/bats-core/bats-core/blob/master/docs/source/writing-tests.md#special-variables)*

2021-06-24 10:51 UTC, angelbarrera92 commented on scripts/e2e/test_job.template
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
Why not using the kustomize project you prepared?

2021-06-24 12:48 UTC, nandajavarma commented on cmd/service-endpoints-check/main.go
> +	rootCmd.PersistentFlags().StringVar(&kubeCfgFile, "kubeconfig", "",
You are right! fixed it!

2021-06-24 12:49 UTC, nandajavarma commented on deployments/kustomization.yaml
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
Done! super clean!

2021-06-24 12:50 UTC, nandajavarma commented on deployments/role-binding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Yeah it is definitely a fair point. So it makes sense to not have it in deployment file. Currently I have put both just as a proof that you can use either. I will move cluster role binging file out of the deployment. But may be I can put one in one of the examples to show it works with that too.

2021-06-24 12:50 UTC, nandajavarma commented on deployments/cluster-role-binding.yaml
> +  namespace: default
cleaned!

2021-06-24 12:51 UTC, nandajavarma commented on examples/cluster-role-binding.yaml
> +    namespace: default
Yeah fair. Will do :)

2021-06-24 12:52 UTC, nandajavarma commented on scripts/e2e/run.sh
> +KUBECONFIG=$(pwd)/kubeconfig TEST_PATH=$(pwd)/scripts/e2e/ CONTAINER_IMAGE=${1} bats -t ./scripts/e2e/tests.sh
Actually I used temp dir as a current path to get the template file from. It looked like bats doesn't provide a variable for that. So I used a pwd (which is the root of the repo) + /scripts/e2e.

2021-06-24 12:53 UTC, nandajavarma commented on scripts/e2e/run.sh
> +KUBECONFIG=$(pwd)/kubeconfig TEST_PATH=$(pwd)/scripts/e2e/ CONTAINER_IMAGE=${1} bats -t ./scripts/e2e/tests.sh
I could rename it to something more meaningful like $CURRENT_DIR.

2021-06-24 12:54 UTC, nandajavarma commented on deployments/cluster-role-binding.yaml
> +kind: ClusterRoleBinding
Moved cluster binding out of deployment directory. :)

2021-06-25 08:17 UTC, nandajavarma commented on scripts/e2e/run.sh
> +KUBECONFIG=$(pwd)/kubeconfig TEST_PATH=$(pwd)/scripts/e2e/ CONTAINER_IMAGE=${1} bats -t ./scripts/e2e/tests.sh
removed! :)

2021-06-28 15:08 UTC, angelbarrera92 commented on examples/nginx-pod/README.md
> +$ kubectl apply -k ./
We use to do `kustomize build . | kubectl apply -f -`
The reason is to be able to know (control) wich is the kustomize version used. Is not clear wich version is bundled with `kubectl`

2021-06-28 15:09 UTC, angelbarrera92 commented on pkg/services/main_test.go
I like to have unit tests :)

In the future, consider doing just one asertion per test. This will increase the number of test and can give us more granularity/information when a test fails

2021-06-28 15:10 UTC, angelbarrera92 approved these changes
LGTM! Minor comments, not blocking to start merging this.
Awesome work @nandajavarma

2021-06-28 15:12 UTC, nandajavarma commented on pkg/services/main_test.go
Noted! I will open an MR to fix this after the merge.

2021-06-28 15:14 UTC, nandajavarma commented on examples/nginx-pod/README.md
> +$ kubectl apply -k ./
understood. fixed!

2021-06-28 15:58 UTC, merged